sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.7.1
before_install:
  - sudo docker-compose build
  - sudo docker-compose up -d
script:
  - cd demo-service/ && npm test
after_script:
  - docker-compose down