version: '2'
services:
  demo-service:
    build: ./demo-service
    container_name: users_service
    ports:
     - "8123:8123"
    links:
      - db:db
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./demo-database